---
version: "3"
services:
  tflint:
    image: wata727/tflint:0.18.0
    working_dir: /app/terraform
    volumes:
      - ${PWD}:/app:z
  terraform:
    image: hashicorp/terraform:0.12.29
    working_dir: /app/terraform
    volumes:
      - ${PWD}:/app:z
    env_file:
      - .env
