# This workflow will deploy a new task definition to Amazon ECS based on the image pushed to ECR, when a merge is created

name: Deploy Worpress image
on:
  push:
    branches: 
    - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy image
      env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: make deploy-wp
      
