# This workflow will deploy a new task definition to Amazon ECS based on the image pushed to ECR, when a merge is created

name: Deploy Wordpress image
on:
  push:
    branches: 
    - master
    paths: 'docker/'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Build and tag image
      run: make build

    - name: Push image to Amazon ECR
      run: make publish
    
    - name: Deploy image
      run: make deploy-wp
      
