on:
  pull_request:
    branches:
      - master

name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_MESSAGE: "Keep forward :rocket:"
          SLACK_TITLE: Post Title
          SLACK_USERNAME: Group2-DevOps
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
