
name: 'Terraform Master Push'

on:
  push:
    branches:
    - master

jobs:
  terraform:
    name: 'Terraform Push'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Plan
      run: make plan

    - name: Apply
      run: make apply

