---
steps:
  - name: Checkout latest master
    uses: actions/checkout@v2

  - name: Build and push Wordpress Docker Image to ECR
    uses: docker/build-push-action@v1
    with:
      dockerfile: wordpress-image/Dockerfile
      username: ${{ secrets.REPO_USERNAME }}
      password: ${{ secrets.REPO_PASSWORD }}
      repository: ${{ secrets.REPO_URL }}/wordpress
      tag_with_sha: true
